### ISSUE TITLE
storage

### ISSUE THREAD

**Issue by Kevin222004** [Kevin222004/GitHub-action#3]
**1) JavaParser**

- [ ]  VoidMethodCallMutator (1)
- [ ]  NullReturnValsMutator (1)
- [ ]  NakedReceiverMutator (1)

------

**2) DetailAstImpl**

- [ ]  NonVoidMethodCallMutator (3)
- [ ]  MemberVariableMutator (3)

------

**3) JavadocPropertiesGenerator**

- [ ] JavadocPropertiesGenerator (1)
- [ ]  NakedReceiverMutator (1)

------

**4) XmlLoader**

- [ ] ArgumentPropagationMutator (1)
- [ ] NonVoidMethodCallMutator (1)

------

**5) JavadocNodeImpl**

- [ ] ArgumentPropagationMutator (2)
- [ ] NonVoidMethodCallMutator (1)
- [ ]  NakedReceiverMutator (1)

-----

**6) JavadocTagInfo$15**

- [ ] RemoveConditionalMutator_EQUAL_IF (2)

------

**7) JavadocTypeCheck**

- [ ] NonVoidMethodCallMutator (2)
- [ ]  MemberVariableMutator (1)
- [ ]  RemoveConditionalMutator_EQUAL_IF (4)
- [ ] NakedReceiverMutator (1)

-----

**8)  JavadocTagInfo$14 **

- [ ] RemoveConditionalMutator_EQUAL_IF (1)

------

**9) AtclauseOrderCheck**

- [ ]  NakedReceiverMutator (1)

------

**10) JavadocTagInfo$11**

- [ ] RemoveConditionalMutator_EQUAL_IF (1)

------

**11) HtmlTag**

- [ ]  ArgumentPropagationMutator (1)

-------

**12) JavadocContentLocationCheck**

- [ ]  MemberVariableMutator (1)

------

**13) JavadocParagraphCheck**

- [ ]  MemberVariableMutator (1)
- [ ]  RemoveConditionalMutator_EQUAL_ELSE (3)
- [ ]  RemoveConditionalMutator_EQUAL_IF (1)

------

**14) TagParser**

- [ ]  ArgumentPropagationMutator (3)
- [ ]  NonVoidMethodCallMutator (2)
- [ ]  RemoveConditionalMutator_EQUAL_ELSE (3)
- [ ]  RemoveConditionalMutator_EQUAL_IF (1)
- [ ]  NakedReceiverMutator (1)
- [ ]  RemoveConditionalMutator_ORDER_ELSE (1)

----

**15) JavadocMissingLeadingAsteriskCheck**

- [ ]  RemoveConditionalMutator_EQUAL_IF (1)

----

**16) JavadocTagContinuationIndentationCheck**

- [ ]  ArgumentPropagationMutator (1)
- [ ]  NonVoidMethodCallMutator (1)
- [ ] RemoveConditionalMutator_EQUAL_IF (1)
- [ ]  NakedReceiverMutator (1)

-----

**17) SummaryJavadocCheck**

- [ ]  RemoveConditionalMutator_EQUAL_IF (1)
         https://github.com/checkstyle/checkstyle/pull/13329
         
-------

**18) AbstractJavadocCheck**

- [ ]  NonVoidMethodCallMutator (4)
- [ ]  RemoveConditionalMutator_EQUAL_ELSE (1)
- [ ] RemoveConditionalMutator_EQUAL_IF (2)

---------

**19) JavadocMethodCheck$Token**

- [ ]  NonVoidMethodCallMutator (2)
- [ ] MemberVariableMutator (2)

--------

**20) MissingJavadocMethodCheck**

- [ ] RemoveConditionalMutator_EQUAL_ELSE (2)
- [ ] MemberVariableMutator (1)
- [ ] RemoveConditionalMutator_EQUAL_IF (2)

--------

**21) RequireEmptyLineBeforeBlockTagGroupCheck**

- [ ]  RemoveConditionalMutator_ORDER_IF (1)

--------

**22) JavadocStyleCheck**

- [ ]  NonVoidMethodCallMutator (6)
- [ ]  RemoveConditionalMutator_EQUAL_ELSE (3)
- [ ] RemoveConditionalMutator_EQUAL_IF (3)
- [ ] RemoveIncrementsMutator (1)
- [ ]  NakedReceiverMutator (3)

--------

**23) NonEmptyAtclauseDescriptionCheck**

- [ ]  NonVoidMethodCallMutator (1)

--------

**24) JavadocMethodCheck**

- [ ]  ArgumentPropagationMutator (2)
- [ ]  NonVoidMethodCallMutator (12)
         https://github.com/checkstyle/checkstyle/pull/13337
         https://github.com/checkstyle/checkstyle/pull/13356 (6 mutations)
- [ ]  RemoveConditionalMutator_EQUAL_ELSE (2)
         https://github.com/checkstyle/checkstyle/pull/13356
- [ ]  MemberVariableMutator (2)
         https://github.com/checkstyle/checkstyle/pull/13356 (2 mutations)
- [ ] RemoveConditionalMutator_EQUAL_IF (9)
       https://github.com/checkstyle/checkstyle/pull/13337 (2 Mutations)
       https://github.com/checkstyle/checkstyle/pull/13356 (3 Mutations)
- [ ]  NakedReceiverMutator (4)
         https://github.com/checkstyle/checkstyle/pull/13356 (2 Mutations)

--------

**25) JavadocUtil**

- [ ] NonVoidMethodCallMutator (3)
       https://github.com/checkstyle/checkstyle/pull/13379 (Cover 2 Mutation)

--------

**26) XpathUtil**

- [ ]  NakedReceiverMutator (1)

--------

**27) CodePointUtil**

- [ ]  ArgumentPropagationMutator (3)
- [ ]  NonVoidMethodCallMutator (1)
- [ ]  RemoveConditionalMutator_EQUAL_ELSE (1)
- [ ]  RemoveConditionalMutator_ORDER_ELSE (1)

--------

**28) AnnotationUtil**

- [ ] RemoveConditionalMutator_EQUAL_ELSE (1)
        https://github.com/checkstyle/checkstyle/pull/13415

--------

**29) ScopeUtil**

- [ ] RemoveConditionalMutator_EQUAL_IF (4)
- [ ] NakedReceiverMutator (3)
        https://github.com/checkstyle/checkstyle/pull/13379

--------

**30) CommonUtil**

- [ ]  RemoveConditionalMutator_EQUAL_ELSE (2)
- [ ]  NonVoidMethodCallMutator (1)
- [ ]  RemoveConditionalMutator_EQUAL_IF (2)
- [ ]  NakedReceiverMutator (2)

--------

**31) TokenUtil**

- [ ]  NonVoidMethodCallMutator (1)

--------

**32) BlockCommentPosition**

- [ ] RemoveConditionalMutator_EQUAL_IF (5)
        https://github.com/checkstyle/checkstyle/pull/13379 (Cover 4 Mutation)
        https://github.com/checkstyle/checkstyle/pull/13424
- [ ]  NakedReceiverMutator (1)
         https://github.com/checkstyle/checkstyle/pull/13416

--------

**33) ModuleReflectionUtil**

- [ ]  NakedReceiverMutator (1)

--------

35) MultilineDetector

- [ ]  NonVoidMethodCallMutator (1)

--------

37) RegexpCheck

- [ ] NonVoidMethodCallMutator (1)
        https://github.com/checkstyle/checkstyle/pull/13383
- [ ]  MemberVariableMutator (3)
      https://github.com/checkstyle/checkstyle/pull/13383 (cover all 3 mutations)

--------

**39) DetectorOptions**

- [ ]  MemberVariableMutator (1)

--------

**41) SuppressionCommentFilter**

- [ ]  NonVoidMethodCallMutator (1)

 ------------

42) SuppressWithNearbyCommentFilter

- [ ]  NonVoidMethodCallMutator (1)

------------
 
 43) SuppressFilterElement
 
- [ ]  NonVoidMethodCallMutator (3)
- [ ]  MemberVariableMutator (17) 10 mutations delayed until hcoles/pitest#1230
    https://github.com/checkstyle/checkstyle/pull/13396

----------

44) SuppressWithNearbyCommentFilter$Tag
- [ ]  MemberVariableMutator (2) 2 mutations delayed until hcoles/pitest#1230
 
--------
 
45) SuppressWithPlainTextCommentFilter
 
- [ ]  NonVoidMethodCallMutator (2)
 
-------
 
- [ ] 46) SuppressWithNearbyTextFilter
 
- [ ]  NonVoidMethodCallMutator (1)
- [ ]  RemoveConditionalMutator_EQUAL_IF (1)
 
--------
 
47) XpathFilterElement

- [ ]  ArgumentPropagationMutator (1)
- [ ]  NonVoidMethodCallMutator (4)
- [ ]  MemberVariableMutator (10) -->  7 Mutations delay until hcoles/pitest#1230
- [ ]  NakedReceiverMutator (1)
 
----------
 
48) SuppressWithPlainTextCommentFilter$Suppression
 
- [ ]  MemberVariableMutator (4) 2 mutations delayed until hcoles/pitest#1230
 
----------

- [ ] 50) SuppressionXpathSingleFilter 3 mutations delayed until hcoles/pitest#1230
 
- [ ]  MemberVariableMutator (3)
 
-----------
 
51) SuppressionCommentFilter$Tag
 
- [ ]  MemberVariableMutator (2) 2 mutations delayed until hcoles/pitest#1230

--------------

52) SuppressionXpathFilter
 
- [ ]  NonVoidMethodCallMutator (1)
 
--------
 
- [ ] 53) SuppressionFilter
 
- [ ]  MemberVariableMutator (2)
- [ ]  EmptyObjectReturnValsMutator (1)
 
-------
 
54) SuppressionsStringPrinter
 
- [ ]  ArgumentPropagationMutator (1)
- [ ]  NonVoidMethodCallMutator (1)
- [ ]  NakedReceiverMutator (1)
 
------
 
55) JavadocDetailNodeParser

- [ ]  NonVoidMethodCallMutator (1)
 
------------
 
**56) TreeWalker**
 
- [ ]  ArgumentPropagationMutator (1)
- [ ]  NonVoidMethodCallMutator (3)
- [ ]  NakedReceiverMutator (3)
- [ ]  EmptyObjectReturnValsMutator (1)
 
---------
 
**57) DetailNodeTreeStringPrinter**
 
- [ ]  ArgumentPropagationMutator (1)
- [ ]  NonVoidMethodCallMutator (1)
- [ ]  NakedReceiverMutator (1)
 
----------
 
**58) CheckstyleAntTask$Property**
 
- [ ]  EmptyObjectReturnValsMutator (1)

---------
 
**59) CheckstyleAntTask**
 
- [ ]  ArgumentPropagationMutator (4)
- [ ]  NonVoidMethodCallMutator (15)
- [ ]  MemberVariableMutator (2)

---------

**60) PackageObjectFactory**

- [ ]  NonVoidMethodCallMutator (1)
- [ ]  RemoveConditionalMutator_EQUAL_IF (2)
- [ ]  NakedReceiverMutator (1)

---------

**61) SarifLogger**

- [ ]  ArgumentPropagationMutator (1)
- [ ]  NonVoidMethodCallMutator (2)

-----------

**62) ConfigurationLoader$InternalLoader**

- [ ]  ArgumentPropagationMutator (1)
- [ ]  NonVoidMethodCallMutator (2)

-----------

**63) LocalizedMessage**

- [ ]  ArgumentPropagationMutator (1)
- [ ]  MemberVariableMutator (1)

------------

**64) Checker**

- [ ]  ArgumentPropagationMutator (4)
- [ ]  NonVoidMethodCallMutator (3)
- [ ]  MemberVariableMutator (4)
- [ ]  NakedReceiverMutator (1)

--------

**65) AuditEventDefaultFormatter**

- [ ]  ArgumentPropagationMutator (1)
- [ ]  NonVoidMethodCallMutator (2)

---------

**66) XMLLogger$FileMessages**

- [ ]  ArgumentPropagationMutator (4)

-----------

**67) ConfigurationLoader**

- [ ] NonVoidMethodCallMutator (9)
        https://github.com/checkstyle/checkstyle/pull/13299 (covered 8)

------------

**68) XMLLogger**

- [ ]  ArgumentPropagationMutator (5)
- [ ]  NonVoidMethodCallMutator (2)

-------------

**69) Main**

 - [ ] NonVoidMethodCallMutator (3)

-----------

**70) Main$CliOptions**

- [ ]  NakedReceiverMutator (1)

-------------

**71) DescendantIterator**

- [ ]  MemberVariableMutator (1)

https://github.com/checkstyle/checkstyle/pull/13401

--------------

**73) FollowingIterator**

- [ ]  MemberVariableMutator (2)

     https://github.com/checkstyle/checkstyle/pull/13401
 
------------

**74) PrecedingIterator**

- [ ]  MemberVariableMutator (2)
         https://github.com/checkstyle/checkstyle/pull/13401

--------

**75) AbstractRootNode**

- [ ]  RemoveSwitchMutator_1 (1)
- [ ]  RemoveSwitchMutator_2 (1)
- [ ]  RemoveSwitchMutator_5 (1)
- [ ]  RemoveSwitchMutator_8 (1)
         https://github.com/checkstyle/checkstyle/pull/13398

----------

**76) ReverseListIterator**

- [ ]  MemberVariableMutator (1)

----------

**77) RootNode**

- [ ]  NonVoidMethodCallMutator (1)
- [ ]  PrimitiveReturnsMutator (1)

---------

**78) AbstractElementNode**

- [ ]  ArgumentPropagationMutator (1)
- [ ]  RemoveSwitchMutator_8 (1)
      https://github.com/checkstyle/checkstyle/pull/13398

-------------

**80) DescendantTokenCheck**

- [ ] MemberVariableMutator (2)
        https://github.com/checkstyle/checkstyle/pull/13375

-----------

**88) OrderedPropertiesCheck**

- [ ]  ArgumentPropagationMutator (1)
         https://github.com/checkstyle/checkstyle/pull/13374
 - [ ] NonVoidMethodCallMutator (1) 
          https://github.com/checkstyle/checkstyle/pull/13374
